{ config, pkgs, hostname, inputs, ... }:

let
  # vault-mcp packaged from the upstream repo (see flake.nix vault-mcp-src
  # input). Repo's derivation is system-portable; we callPackage it here so it
  # builds for aarch64-linux against this host's pkgs set.
  vault-mcp = pkgs.callPackage "${inputs.vault-mcp-src}/nix/pkgs/vault-mcp.nix" { };
in

# Pi 400 NixOS host.
#
# Bootstrap order (only when re-flashing or bringing up a new Pi):
#   1. Flash stock NixOS aarch64 SD image, boot Pi with ethernet.
#   2. At Pi console: `passwd nixos` to set a temp password, then
#      `ssh-copy-id nixos@<dhcp-ip>` from the Mac.
#   3. SSH in and run `sudo nixos-generate-config --show-hardware-config`;
#      copy output into ./hardware.nix (it normally won't change between
#      images of the same NixOS release).
#   4. Add the Pi's host ed25519 pubkey (derive an age recipient via
#      `ssh-to-age`) to the &pi400 anchor in repo-root /.sops.yaml; re-key
#      nix/secrets/pi400.yaml with `sops updatekeys nix/secrets/pi400.yaml`.
#   5. Build + switch from the UTM aarch64 NixOS VM:
#        nixos-rebuild switch --flake .#pi400 \
#          --target-host nelson@<dhcp-ip> --use-remote-sudo
#
# Remaining imperative bits (future iteration): obsidian-headless install via
# npm under nelson (blocked on upstream pnpm-lock for buildNpmPackage).

{
  imports = [ ./hardware.nix ];

  networking.hostName = hostname;
  time.timeZone = "America/New_York";

  nixpkgs.config.allowUnfreePredicate = pkg:
    builtins.elem (pkgs.lib.getName pkg) [ "obsidian" "claude-code" ];

  nix.settings = {
    experimental-features = [ "nix-command" "flakes" ];
    trusted-users = [ "@wheel" ];
  };

  # Bootloader for Raspberry Pi (no GRUB — use the SD's extlinux setup)
  boot.loader.grub.enable = false;
  boot.loader.generic-extlinux-compatible.enable = true;

  # ---- Secrets (sops-nix) ----
  # On the Pi, sops-nix decrypts using the host's SSH ed25519 private key,
  # which was generated by sshd on first boot. The corresponding public key
  # was converted to an age recipient and added to /.sops.yaml.
  sops.defaultSopsFile = ../../secrets/pi400.yaml;
  sops.age.sshKeyPaths = [ "/etc/ssh/ssh_host_ed25519_key" ];

  sops.secrets.tailscale-authkey = {
    # 0400 root by default — only tailscaled reads it.
  };
  sops.secrets.wifi-env = {
    # NM is run by root, so root readability is enough.
  };

  # Networking — NM owns WiFi (uses wpa_supplicant as its backend). Profiles
  # declared here, PSKs substituted at activation from a sops-decrypted env
  # file so plaintext never lands in the Nix store.
  networking.networkmanager.enable = true;
  networking.networkmanager.ensureProfiles = {
    environmentFiles = [ config.sops.secrets.wifi-env.path ];
    profiles = {
      myluigi13 = {
        connection = {
          id = "myluigi13";
          type = "wifi";
          autoconnect = "true";
          autoconnect-priority = "100";
        };
        wifi = {
          ssid = "myluigi13";
          mode = "infrastructure";
        };
        wifi-security = {
          key-mgmt = "wpa-psk";
          psk = "$WIFI_MYLUIGI13_PSK";
        };
        ipv4.method = "auto";
        ipv6.method = "auto";
      };
      iphone = {
        connection = {
          id = "iPhone";
          type = "wifi";
          autoconnect = "true";
          autoconnect-priority = "-1";
        };
        wifi = {
          ssid = "iPhone";
          mode = "infrastructure";
        };
        wifi-security = {
          key-mgmt = "wpa-psk";
          psk = "$WIFI_IPHONE_PSK";
        };
        ipv4.method = "auto";
        ipv6.method = "auto";
      };
    };
  };

  # Users
  users.users.nelson = {
    isNormalUser = true;
    description = "Nelson";
    extraGroups = [ "wheel" "networkmanager" "video" ];
    shell = pkgs.zsh;
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILXHbH6xriFbjHuXMWDa8M8QTzZfnMZ+hHVTuKyw3LBT nelson@wham.studio"
    ];
  };
  security.sudo.wheelNeedsPassword = false;
  programs.zsh.enable = true;

  # SSH — keys only
  services.openssh = {
    enable = true;
    settings = {
      PasswordAuthentication = false;
      PermitRootLogin = "no";
    };
  };

  # Tailscale — authKeyFile is loaded once at first up; subsequent boots
  # use the persisted machine state in /var/lib/tailscale.
  services.tailscale = {
    enable = true;
    authKeyFile = config.sops.secrets.tailscale-authkey.path;
    extraUpFlags = [ "--ssh" "--accept-routes" ];
  };

  # Packages
  environment.systemPackages = with pkgs; [
    claude-code
    git
    vim
    ripgrep
    fd
    jq
    htop
    tmux
    tree
    nodejs_22  # for obsidian-headless (npm-installed under nelson)
  ];

  # Obsidian Sync via the official headless CLI (`ob`). One-time bootstrap:
  #   npm config set prefix ~/.npm-global
  #   npm install -g obsidian-headless
  #   ob login                                    # interactive
  #   ob sync-list-remote                         # confirm vault name
  #   mkdir -p ~/obsidian && cd ~/obsidian
  #   ob sync-setup --vault "<name>"
  #   sudo systemctl enable --now obsidian-sync
  systemd.services.obsidian-sync = {
    description = "Obsidian Sync (headless ob daemon)";
    after = [ "network-online.target" ];
    wants = [ "network-online.target" ];
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      Type = "simple";
      User = "nelson";
      Group = "users";
      WorkingDirectory = "/home/nelson/obsidian";
      Environment = [
        "HOME=/home/nelson"
        "PATH=/home/nelson/.npm-global/bin:/run/current-system/sw/bin"
      ];
      ExecStart = "/home/nelson/.npm-global/bin/ob sync --continuous";
      Restart = "on-failure";
      RestartSec = "30s";
    };
  };

  # vault-mcp — local-only MCP server for claude-code on Pi. Sourced from the
  # upstream repo's derivation via flake input (see top of file). Listens on
  # localhost only — no exposure, no auth.
  systemd.services.vault-mcp = {
    description = "Obsidian vault MCP server (local Streamable HTTP)";
    # vault-mcp is a peer of obsidian-sync — both read /home/nelson/obsidian;
    # vault-mcp can serve whatever is on disk independently. Just need network
    # (for the listen socket) before we start.
    after = [ "network.target" ];
    wants = [ "network.target" ];
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      Type = "simple";
      User = "nelson";
      Group = "users";
      Environment = [
        "VAULT_PATH=/home/nelson/obsidian"
        "PORT=8787"
        "HOST=127.0.0.1"
        "AUTH_ENABLED=false"
      ];
      ExecStart = "${vault-mcp}/bin/vault-mcp";
      Restart = "on-failure";
      RestartSec = "10s";
    };
  };

  # Swap — 4 GB RAM is tight when nix evaluates anything large.
  # Build offloading to the Mac should mean this rarely matters, but
  # cheap insurance.
  swapDevices = [{
    device = "/swapfile";
    size = 4096;
  }];

  system.stateVersion = "25.05";
}
