{ config, lib, pkgs, modulesPath, ... }:

# Generated by `nixos-generate-config --show-hardware-config` on the running
# Pi after first boot. Re-generate (rather than hand-edit) if filesystems
# change.

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/44444444-4444-4444-8888-888888888888";
    fsType = "ext4";
  };

  # NetworkManager owns DHCP — see default.nix
  # networking.useDHCP intentionally not set here

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
