# Prefix: C-Space
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Splits
unbind '"'
unbind %
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Window navigation
bind -n S-Left  previous-window
bind -n S-Right next-window

# Mouse
set -g mouse on
unbind -n MouseDrag1Pane
unbind -T copy-mode MouseDrag1Pane
bind m setw mouse

# Copy mode
bind-key -T copy-mode v send-keys -X begin-selection
bind-key -T copy-mode y send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode r send-keys -X rectangle-toggle

# Reload config
bind r source-file ~/.config/tmux/tmux.conf \; display 'Reloaded tmux config'

# Edit config
bind e new-window -n 'tmux.conf' \
  "zsh -c '${EDITOR} ~/.config/tmux/tmux.conf && tmux source ~/.config/tmux/tmux.conf'"

# Shell
set -g default-shell /bin/zsh
set -g default-command /bin/zsh

# Terminal
set -g default-terminal "alacritty"
set -sa terminal-overrides ",xterm*:Tc"

# Sensible defaults
set -s escape-time 0
set -g history-limit 50000
set -g display-time 4000
set -g focus-events on
set -g status-keys emacs
set -gw aggressive-resize on

# Windows start at 1
set -g base-index 1
set -g pane-base-index 0
set -g automatic-rename on
set -g set-titles on

# Status bar
set -g status on
set -g status-interval 5
set -g status-left-length 30
set -g status-right-length 150

set -g status-style bg=colour237,fg=colour223
set -g message-style bg=colour239,fg=colour223
set -g message-command-style bg=colour239,fg=colour223

set -g pane-border-style fg=colour239
set -g pane-active-border-style fg=colour10

set -g display-panes-active-colour colour1
set -g display-panes-colour colour237

set -gw clock-mode-colour colour109
set -gw window-status-bell-style bg=colour167,fg=colour235
set -gw window-status-style bg=colour10,fg=colour237
set -gw window-status-current-style bg=red,fg=colour237
set -gw window-status-activity-style bg=colour237,fg=colour248

set -g status-left "\
#[fg=colour7, bg=colour241]#{?client_prefix,#[bg=colour167],} ❐ #S \
#[fg=colour241, bg=colour237]#{?client_prefix,#[fg=colour167],}#{?window_zoomed_flag, 🔍,}"

set -g status-right "\
#[fg=colour10, bg=colour237]\
#[fg=colour237, bg=colour10] %b %d '%y \
#[fg=colour237, bg=colour10]\
#[fg=colour241, bg=colour237]\
#[fg=colour7, bg=colour241]%H:%M "

set -gw window-status-current-format "\
#[fg=colour237, bg=colour10]\
#[fg=colour239, bg=colour10] #I* \
#[fg=colour239, bg=colour10, bold] #W \
#[fg=colour10, bg=colour237]"

set -gw window-status-format "\
#[fg=colour237,bg=colour239,noitalics]\
#[fg=colour223,bg=colour239] #I \
#[fg=colour223, bg=colour239] #W \
#[fg=colour239, bg=colour237]"
